<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\UrbanSync.Application\UrbanSync.Application.csproj" />

    <ProjectReference
      Include="..\UrbanSync.Infrastructure\UrbanSync.Infrastructure.csproj" />
  </ItemGroup>

</Project>
